## Задание 1

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('olist_order_items_dataset.csv')

prices = df['price'].values
freights = df['freight_value'].values

def calculate_slow(prices, freights):
  prices_list = list(prices)
  freights_list = list(freights)
  results = []
  for p, f in zip(prices_list, freights_list):
    if p > 500:
      discount = 0.15
    elif p > 100:
      discount = 0.10
    else:
      discount = 0.0
    final_price = (p * (1 - discount)) + f
    results.append(final_price)
  return results

test_results = calculate_slow(prices[:5], freights[:5])
print('res', test_results)

def calculate_fast(prices, freights):
  conditions = [
      prices > 500,
      prices > 100
  ]
  choices = [
      0.15,
      0.10
  ]
  discounts_array = np.select(conditions, choices, default=0.0)
  final_prices = (prices * (1 - discounts_array)) +  freights
  return final_prices

test_results_fast = calculate_fast(prices[:5], freights[:5])
print('fast res', test_results_fast)
print('совпадение результата', np.allclose(calculate_slow(prices, freights), calculate_fast(prices, freights)))

res [np.float64(72.19), np.float64(235.84), np.float64(196.97), np.float64(25.78), np.float64(198.05)]
fast res [ 72.19 235.84 196.97  25.78 198.05]
совпадение результата True


In [2]:
t_slow = %timeit -o calculate_slow(prices, freights)

13.8 ms ± 70.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
t_fast = %timeit -o calculate_fast(prices, freights)

263 μs ± 11.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
print(f'ускорение: {t_slow.average / t_fast.average:.1f} раз')

ускорение: 52.5 раз


## Задание 2

In [5]:
items_array = df.to_numpy()

mean_price = np.mean(prices)
std_price = np.std(prices)
limit = mean_price + 3 * std_price
anomalies = items_array[prices > limit]
print(limit, len(anomalies))
print(anomalies[:5])

671.553077967881 1966
[['000576fe39319847cbb9d288c5617fa6' 1 '557d850972a7d6f792fd18ae1400d9b6'
  '5996cddab893a4652a15592fb58ab8db' '2018-07-10 12:30:45' 810.0 70.75]
 ['0017afd5076e074a48f1f1a4c7bac9c5' 1 'fe59a1e006df3ac42bf0ceb876d70969'
  '25c5c91f63607446a97b143d2d535d31' '2017-04-24 22:25:19' 809.1 44.29]
 ['00c9474e0334f7a4ffc8c3a8bd21a51e' 1 '4b2653088591de362e6ba85b4a474c75'
  '610f72e407cdd7caaa2f8167b0163fd8' '2018-05-10 15:50:46' 1050.61 25.13]
 ['00d2559e61b9a0744a0552c35c5ecccb' 1 '44fc450365728c413fefc547592626be'
  'b839e41795b7f3ad94cc2014a52f6796' '2018-06-13 12:57:03' 849.0 23.52]
 ['011a43bc9bb525517251ebb3ebc99b69' 1 'ca7966fa77959536468be3c6ce1f19e1'
  '610f72e407cdd7caaa2f8167b0163fd8' '2018-05-03 18:09:38' 899.0 21.2]]


In [6]:
random_indices = np.random.choice(len(items_array), size = 100, replace = False)
random_rows = items_array[random_indices]
print(random_rows.shape)
print(random_rows[:5])

(100, 7)
[['1ca9b19a39f0b18a4a1470eba6eb5cda' 1 '656e0eca68dcecf6a31b8ececfabe3e8'
  'e9bc59e7b60fc3063eb2290deda4cced' '2017-05-25 11:15:20' 93.9 17.1]
 ['008a40c2b8b21893e04945ce58854b55' 1 '016711f78a6a87696645db0a6a834826'
  'a5cba26a62b8b4d0145b68b841e62e7f' '2018-05-04 20:54:23' 99.0 13.0]
 ['3806e97292af7b9430f6981372925843' 2 'ee92961b88199a0d4329a6beca8f63da'
  '78c99c6dff4eeae5be99bf635ed21e3f' '2017-08-15 22:45:19' 39.9 16.11]
 ['9e4b90eef41ed5a85e2e2f8bef415075' 1 '610c673331ac3c4fa0f393ce5af9aa2e'
  '8b321bb669392f5163d04c59e235e066' '2018-04-03 17:27:53' 13.65 7.39]
 ['faf5353e864ae43e76a472b039d0a1a2' 2 '5113c9a5037013b0a750444df6dec60f'
  '54a1852d1b8f10312c55e906355666ee' '2018-03-28 17:48:27' 109.99 19.78]]


## Задание 3

In [7]:
products_df = pd.read_csv('olist_products_dataset.csv')
products_df = products_df.dropna(subset = ['product_length_cm', 'product_height_cm', 'product_width_cm'])
L = products_df['product_length_cm'].values
H = products_df['product_height_cm'].values
W = products_df['product_width_cm'].values
volumetric_weight = (L * H * W) / 6000
print(volumetric_weight[:5])

[0.37333333 1.8        0.405      0.45066667 0.73666667]


In [8]:
price_matrix = np.random.uniform(10, 1000, size = (1000, 5))
region_coefs = np.array([1.00, 1.10, 0.95, 1.20, 1.05])

regional_prices = price_matrix * region_coefs

print(price_matrix.shape, region_coefs.shape, regional_prices.shape)
print(price_matrix[:3].round(2))
print(regional_prices[:3].round(2))

(1000, 5) (5,) (1000, 5)
[[ 10.92 330.09 931.69  53.79  21.6 ]
 [450.07 218.38 928.34 313.32 380.58]
 [374.42 441.25 129.77 243.3  805.12]]
[[ 10.92 363.1  885.11  64.55  22.68]
 [450.07 240.22 881.92 375.98 399.61]
 [374.42 485.37 123.28 291.96 845.37]]


## Задание 4

In [9]:
feature_cols = ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
features_df = products_df.dropna(subset = feature_cols).head(1000)
X = features_df[feature_cols].values

X_norm = (X - X.mean(axis = 0)) / X.std(axis = 0)
print(X_norm.shape)
print(X_norm.mean(axis = 0).round(2), X_norm.std(axis = 0).round(2))

(1000, 4)
[-0.  0.  0.  0.] [1. 1. 1. 1.]


In [10]:
selected_idx = 0
selected = X_norm[selected_idx]

similarities = (X_norm @ selected) / (np.linalg.norm(X_norm, axis = 1) * np.linalg.norm(selected))

top_idx = np.argsort(similarities)[::-1][1:6]
print('выбранный товар:', features_df['product_id'].values[selected_idx])
print(features_df.iloc[top_idx][['product_id'] + feature_cols].assign(similarity = similarities[top_idx].round(4)))

выбранный товар: 1e9e8ef04dbcff4541ed26657ea517e5
                           product_id  product_weight_g  product_length_cm  \
590  35255921c732e0e9319097469d856cd5             400.0               18.0   
232  532d7f19b8005e415f5b98a1cf4a8690             400.0               16.0   
877  3099fd60323d4c647f2515690394bfb2             217.0               17.0   
161  3014e35fd70fce29095ced5cdc89f4ce             125.0               17.0   
407  15571dce56ff7d152dab99a0bc8354d5             482.0               18.0   

     product_height_cm  product_width_cm  similarity  
590               11.0              15.0      0.9997  
232               10.0              14.0      0.9995  
877               10.0              14.0      0.9993  
161               10.0              14.0      0.9990  
407               11.0              16.0      0.9988  
